apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: hammerfall
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: hammerfall
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: closer
  namespace: hammerfall
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-prepare
  namespace: hammerfall
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-publisher
  namespace: hammerfall
  annotations:
    iam.gke.io/gcp-service-account: hf-reference-kpub@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-audit
  namespace: hammerfall
  annotations:
    iam.gke.io/gcp-service-account: hf-reference-kaudit@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-projection
  namespace: hammerfall
  annotations:
    iam.gke.io/gcp-service-account: hf-reference-kproj@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: hammerfall
