apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- config.yaml
- dependencies.yaml
- api.yaml
- web.yaml
- web-proxy.yaml
- sidekiq.yaml
- outbox-publisher.yaml
- kafka-outbox-publisher.yaml
- kafka-audit-consumer.yaml
- kafka-projection-consumer.yaml
- auction-closer.yaml
- reconciliation-scheduler.yaml
