source "https://rubygems.org"

ruby "4.0.6"
gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "pg", "~> 1.6"
gem "puma", "~> 8.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 8.0"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
