source "https://rubygems.org"

ruby "4.0.6"
gem "rails", "~> 8.1.3", ">= 8.1.3.1"
# Rails 8.1 passes positional parser options; JSON 3 requires keyword options.
gem "json", "~> 2.0"
gem "pg", "~> 1.6"
gem "puma", "~> 8.0"
gem "bootsnap", require: false
gem "sidekiq", "~> 8.1"
gem "rdkafka", "~> 0.30.0"
gem "redis-client", "~> 0.30"
gem "opentelemetry-sdk", "~> 1.13"
gem "opentelemetry-exporter-otlp", "~> 0.37"
gem "opentelemetry-metrics-sdk", "~> 0.19"
gem "opentelemetry-exporter-otlp-metrics", "~> 0.13"
gem "opentelemetry-instrumentation-rack", "~> 0.31"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 8.0"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
